version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=webapp_user
      - POSTGRES_DB=webapp
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
  redis:
    image: redis
    ports:
      - 6379:6379