version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=webapp_user
      - POSTGRES_DB=webapp
    ports:
      - "5432:5432"
